sudo: required
services:
  - docker

language: generic
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: flask
  env: Flask-env
  bucket-name: elasticbeanstalk-us-east-1-276874294099
  bucket-path: flask-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY